/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.eec.juegogato;

import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.eec.mapping.JButtonToIntegerArray;
import org.eec.utils.ArrayUtils;
import org.eec.games.boards.*;

/**
 *
 * @author erick
 */
public class JFrameJuegoGato extends javax.swing.JFrame {

    private boolean tiro = true;
    private JButton[] arregloBotones;
    private JButtonToIntegerArray jButtonToIntArray;
    private ArrayUtils<Integer> arrayUtils;
    private TableroGato tableroGato;
    /**
     * Creates new form JFrameJuegoGato
     */
    public JFrameJuegoGato() {
        initComponents();
        arregloBotones = new JButton[9];
        jButtonToIntArray = new JButtonToIntegerArray();
        arrayUtils = new ArrayUtils<>();
        tableroGato = new TableroGato();
        
        arregloBotones[0] = this.jButton1;
        arregloBotones[1] = this.jButton2;
        arregloBotones[2] = this.jButton3;
        arregloBotones[3] = this.jButton4;
        arregloBotones[4] = this.jButton5;
        arregloBotones[5] = this.jButton6;
        arregloBotones[6] = this.jButton7;
        arregloBotones[7] = this.jButton8;
        arregloBotones[8] = this.jButton9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Gato - EEC (2010067) - Erick Escam");

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.getAccessibleContext().setAccessibleName("3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // 'tiro' como bandera booleana para 'controlar'
        // 'el turno' de CADA JUGADOR (J1 : 'X') / (J2 : 'O')
        // para que el Control de Turnos de JUGADOR sea efectivo
        // mediante la bandera <<tiro>> es NECESARIO INVOCAR el
        // método jButtonX.SETENABLED(false) PARA DESACTIVAR el botón
        // justo después de que el usuario ha hecho clic en el.
        // Al desactivar el botón SE EVITA QUE EL USUARIO pueda interactuar con el botón
        // ('el usuario YA NO PUEDE HACER CLIC de nuevo sobre el botón').
        if(tiro){
            jButton1.setText("X");
            tiro = false;
        }else{
            jButton1.setText("O");
            tiro = true;
        }
        jButton1.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tiro){
            jButton2.setText("X");
            tiro = false;
        }else{
            jButton2.setText("O");
            tiro = true;
        }
        jButton2.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tiro){
            jButton3.setText("X");
            tiro = false;
        }else{
            jButton3.setText("O");
            tiro = true;
        }
        // "Deshabilitar" el botón (ya NO se puede hacer clic en el botón)
        // justo después de haber hecho clic.
        jButton3.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // 'tiro' como bandera booleana para 'controlar'
        // 'el turno' de CADA JUGADOR (J1 : 'X') / (J2 : 'O')
        if(tiro){
            jButton4.setText("X");
            tiro = false;
        }else{
            jButton4.setText("O");
            tiro = true;
        }
        // "Deshabilitar" el botón (ya NO se puede hacer clic en el botón)
        // justo después de haber hecho clic.
        jButton4.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(tiro){
            jButton5.setText("X");
            tiro = false;
        }else{
            jButton5.setText("O");
            tiro = true;
        }
        // "Deshabilitar" el botón (ya NO se puede hacer clic en el botón)
        // justo después de haber hecho clic.
        jButton5.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(tiro){
            jButton6.setText("X");
            tiro = false;
        }else{
            jButton6.setText("O");
            tiro = true;
        }
        // "Deshabilitar" el botón (ya NO se puede hacer clic en el botón)
        // justo después de haber hecho clic.
        jButton6.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(tiro){
            jButton7.setText("X");
            tiro = false;
        }else{
            jButton7.setText("O");
            tiro = true;
        }
        // "Deshabilitar" el botón (ya NO se puede hacer clic en el botón)
        // justo después de haber hecho clic.
        jButton7.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(tiro){
            jButton8.setText("X");
            tiro = false;
        }else{
            jButton8.setText("O");
            tiro = true;
        }
        // "Deshabilitar" el botón (ya NO se puede hacer clic en el botón)
        // justo después de haber hecho clic.
        jButton8.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(tiro){
            jButton9.setText("X");
            tiro = false;
        }else{
            jButton9.setText("O");
            tiro = true;
        }
        // "Deshabilitar" el botón (ya NO se puede hacer clic en el botón)
        // justo después de haber hecho clic.
        jButton9.setEnabled(false);
        
        validarFinJuego();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameJuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameJuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameJuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameJuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameJuegoGato().setVisible(true);
            }
        });
    }
    
    public void validarFinJuego(){
        String msjFinJuego = "";
        StringBuilder sb;
        boolean isGameOver = false;
        int contador = 0;
        JButton jButtonTmp;
        Integer[][] intArray;
        TicTacToeBoardFullState boardState;
        
        sb = new StringBuilder();
        
        Component[] arregloComponentes;
        
        // arregloComponentes : arreglo de los jButtons [OK - 'Touche']
        arregloComponentes = this.getRootPane().getContentPane().getComponents();
        
        System.out.println("------------- validarFinJuego() ---------------------------");
        /*
         for(Component componente : arregloComponentes){
            contador++;
            if(componente instanceof JButton){
                jButtonTmp = (JButton) componente;
                System.out.println( contador + ".- " + componente.getClass() 
                                    + " nombre del Componente [" + ((JButton) componente).getUIClassID() + "] " + ".texto = " + jButtonTmp.getText());
            }
        }
        */
       
        // .toIntegerArray( buttonArr : JButton[] ) : Integer[][]
        // .toIntegerArray() :: -OK- ${funcionamiento de Acuerdo a lo Esperado}
        intArray = jButtonToIntArray.toIntegerArray( arregloBotones );
        System.out.println( arrayUtils.toBeautyString(intArray) );
        
        tableroGato.setInnerArray( intArray );
        boardState = tableroGato.checkBoardState();
        
        System.out.println( boardState.toString() );
        
        // -- Si el Estado del Tablero es DISTINTO del .status 'Juego en Progreso...'
        // significa que el juego ha llegado a su FIN ${gameOver}
        if( boardState.getEstadoTablero() != TableroGato.EstadoTablero.ONGOING_GAME ){
            isGameOver = true;
            msjFinJuego = boardState.toString();
        }
        
        System.out.println("+++++++++++++++++ validarFinJuego() +++++++++++++++++++++++++++++");
        ///////
        /*
        Idea General de Implementación...
        1.- Mapear TODOS los jButtonX.text a un Array[][] (bi-dimensional)
        de int 
        1: 'X'
        0: 'O'
        -1: 'Empty' ('Celda' VACÍA -no utilizada por ninguno de los jugadores-)
        
        2.- Analizar arreglo[][] ('Tablero de juego')
        buscar condición de finalización del juego::
            2-A> Victoria (de alguno de los 2 jugadores)
            2-B> EMPATE
        
        representar condición de GameOver con bandera booleana ['isGameOver'].
        */
        
        /*
        for( JButton jButton : arregloBotones ){
            sb.append( jButton.getText() ).append(", ");
        }
        
        System.out.println("--Botones (Texto)--");
        System.out.println( sb.toString() );
        System.out.println("++Botones (Texto)++");
        */
        
        
        // formación línea horizontal ('0') ---
        /*
        if( jButton1.getText().equals(jButton2.getText()) && jButton1.getText().equals(jButton3.getText()) ){
            msjFinJuego = String.format("El jugador que ganó FUE : ['%s']", jButton1.getText());
            isGameOver = true;
        }
        */
        
        
        // Mostrar Mensaje en cuadro de diálogo: 'Gano jugador []' / 'EMPATE'
        if(isGameOver){
            JOptionPane.showMessageDialog(this, msjFinJuego);
        }
        
        
        
    } //-- validarFinJuego()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
